name: test

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.os }} / GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ghc: [8.6.5, 8.8.3]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
    - name: Install dependencies
      run: |
        stack --no-terminal --install-ghc test --only-dependencies
    - name: Build
      run: |
        stack --no-terminal build
    - name: Test
      run: |
        stack --no-terminal test --test-arguments --color --coverage-only-library
