name: test

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.os }} / GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ghc: [8.6.5, 8.8.3, 8.10.1]

    # Setup haskell stack
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
    - uses: actions/cache@v2
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack
    - run: stack setup
    - run: stack build --test --no-run-tests --bench --no-run-benchmarks --haddock --no-haddock-deps